#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ritex
Version  : 1.0.1
Release  : 5
URL      : https://rubygems.org/downloads/ritex-1.0.1.gem
Source0  : https://rubygems.org/downloads/ritex-1.0.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
Author::    William Morgan (mailto: wmorgan-ritex@masanjin.net)
License::   GNU GPL version 2

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ritex-1.0.1
gem spec %{SOURCE0} -l --ruby > rubygem-ritex.gemspec

%build
gem build rubygem-ritex.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ritex-1.0.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/ritex-1.0.1
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/ritex-1.0.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/ritex-1.0.1/README
/usr/lib64/ruby/gems/2.3.0/gems/ritex-1.0.1/ReleaseNotes
/usr/lib64/ruby/gems/2.3.0/gems/ritex-1.0.1/lib/ritex.rb
/usr/lib64/ruby/gems/2.3.0/gems/ritex-1.0.1/lib/ritex/lexer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ritex-1.0.1/lib/ritex/mathml/entities.rb
/usr/lib64/ruby/gems/2.3.0/gems/ritex-1.0.1/lib/ritex/mathml/functions.rb
/usr/lib64/ruby/gems/2.3.0/gems/ritex-1.0.1/lib/ritex/mathml/markup.rb
/usr/lib64/ruby/gems/2.3.0/gems/ritex-1.0.1/lib/ritex/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/ritex-1.0.1/test/all.rb
/usr/lib64/ruby/gems/2.3.0/gems/ritex-1.0.1/test/answer-key.yaml
/usr/lib64/ruby/gems/2.3.0/gems/ritex-1.0.1/test/mathml.rb
/usr/lib64/ruby/gems/2.3.0/gems/ritex-1.0.1/test/parser.rb
/usr/lib64/ruby/gems/2.3.0/specifications/ritex-1.0.1.gemspec
